import time
import replapi2
import os
def clear():
  os.system("clear")
print("Welcome random person!")
time.sleep(1)
name = input("Would you mind entering your username here? >")
print("thank you!")
time.sleep(1)
clear()
x = replapi2.UserInfo(name)
print("You bio is '" + x.bio() + "'. Am i right?")
input(">")
clear()
print("I knew it!")
time.sleep(2)
clear()
print("You're probably wondering how i did that.")
input(">")
clear()
print("Well, i used a super cool thing called replapi2.")
input(">")
clear()
print("It's a python module that easily allows you to get replit user data.")
input(">")
clear()
print("Made by ch1ck3n.")